development:
  adapter: postgresql
  encoding: utf8
  database: prognosticator_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: prognosticator_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: prognosticator_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST